version: '3'

services:
  proxy:
    image: traefik:v2.2.7
    command: --api.insecure=true --providers.docker
    networks:
      - web
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml

networks:
  web:
    external:
      name: gomicro